title: Opendata
email: kandimalla.sreeram@gmail.com
description: |
  Opendata India, Local Government Directory
baseurl: "/opendata" # the subpath of your site, e.g. /blog
url: "https://ramseraph.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ramSeraph
github_username:  ramSeraph
github: [metadata]
remote-theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md

style: hacker # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

#footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

#google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
