remote-theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md

style: hacker # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

#footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

#google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
