header_pages:
  - index.md
  - lgd.md
  - about.md

style: hacker # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true
footer: 'Source Code at: <a href="https://github.com/ramSeraph/opendata">Github</a>'

#remote_theme: b2a3e8/jekyll-theme-console
remote_theme: syaning/slim
#remote_theme: minicomp/ed

#google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
