header_pages:
  - index.md
  - lgd.md
  - about.md

#listen_for_clients_preferred_style: true

style: hacker

footer: 'Source Code at: <a href="https://github.com/ramSeraph/opendata">Github</a>'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
#remote_theme: syaning/slim
#remote_theme: minicomp/ed
#remote_theme: pedr0silva/site-theme
#remote_theme: 'MyNameIsCosmo/jekyll-theme-markdown-console'



#google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
