name: BBNL Weekly Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


jobs:
  Archive-BBNL-Main-Page:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: secsi/waybackpy
    steps:
      - name: Save main page
        run: |
          waybackpy --url "https://bbnl.nic.in/" --save --headers

  Archive-BBNL-Usage-Page:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: secsi/waybackpy
    steps:
      - name: Save usage page
        run: |
          waybackpy --url "https://bbnl.nic.in/usage2.pdf" --save --headers

  BBNL-Archive-failure-notify:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: 
      - Archive-BBNL-Main-Page
      - Archive-BBNL-Usage-Page
    if: always() && ( needs.Archive-BBNL-Main-Page.result == 'failure' || needs.Archive-BBNL-Usage-Page.result == 'failure' )
    steps:
      - name: Send PushBullet notification
        run: |
          export PB_API_URL="https://api.pushbullet.com/v2/pushes"
          export PB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          export PB_TITLE="BBNL Page Archival failed"
          export PB_BODY="BBNL Page Archival failed"
          export REQUEST_BODY="{\"title\":\"$PB_TITLE\",\"body\":\"$PB_BODY\",\"type\":\"link\",\"url\":\"$PB_URL\"}" 
          curl -H "Access-Token: ${{ secrets.PB_TOKEN }}" -H "Content-Type: application/json" --data-binary "$REQUEST_BODY" -X POST "$PB_API_URL" > /dev/null
