name: 'PushBullet Alert'
on:
  workflow_call:
    inputs:
      title: 
        description: 'Title in alert( also the body for now )'
        required: true
      which-run:
        description: 'workflow run event whose information needs to be sent'
        required: true
        default: 'self'
      pb-token:
        description: 'Pushbullet Token'
        required: true
        default: '${{ secrets.PB_TOKEN }}'

jobs:
  Send-Alert:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: get-url
        shell: bash
        run: |
          if [[ "${{ inputs.which-run }}" == "self" ]]; then
              echo "::set-output name=url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          elif [[ "${{ inputs.which-run }}" == "from-event" ]]; then
              echo "::set-output name=url::${{ github.event.workflow_run.html_url }}"
          else
              echo "Unsupported input which-run; ${{ inputs.which-run }}"
              exit 1
          fi
      - shell: bash
        run: |
          export PB_API_URL="https://api.pushbullet.com/v2/pushes"
          export PB_URL="${{steps.get-url.outputs.url}}"
          export PB_TITLE="${{inputs.title}}"
          export PB_BODY="${{inputs.body}}"
          export REQUEST_BODY="{\"title\":\"$PB_TITLE\",\"body\":\"$PB_BODY\",\"type\":\"link\",\"url\":\"$PB_URL\"}" 
          curl -H "Access-Token: ${{ inputs.pb-token }}" -H "Content-Type: application/json" --data-binary "$REQUEST_BODY" -X POST "$PB_API_URL" > /dev/null
