name: LGD Monitor Daily Run
on:
  workflow_run:
    workflows:
      - LGD Daily Run
    types: [completed]

jobs:
  RetryTrigger:
    uses: ./.github/workflows/common-rerun-trigger.yml
    secrets: inherit
    with:
      alert-title: "LGD Daily Run failed"
      num-attempts: 3
