name: Monitor Daily Run
on:
  workflow_run:
    workflows:
      - Daily Run
    types: [completed]

jobs:
  RetryTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check to give up
        id: check
        run: |
          export RUN_ID=${{ github.event.workflow_run.id }}
          export RUN_NO=${{ github.event.workflow_run.run_number }}
          export RUN_ATTEMPT=${{ github.event.workflow_run.run_attempt }}
          export CONCLUSION=${{ github.event.workflow_run.conclusion }}
          echo "got workflow run event for $RUN_NUMBER( attempt - $RUN_ATTEMPT ), conclusion - $CONCLUSION"
          if [ "$CONCLUSION" != "failure" ]; then
            echo "setting RERUN to false and SEND_ALERT to false"
            echo "::set-output name=RERUN::false"
            echo "::set-output name=SEND_ALERT::false"
          else
            if [ "$RUN_ATTEMPT" -lt 3 ]; then
              echo "setting RERUN to true and SEND_ALERT to false"
              echo "::set-output name=RERUN::true"
              echo "::set-output name=SEND_ALERT::false"
            else
              echo "setting RERUN to false and SEND_ALERT to true"
              echo "::set-output name=RERUN::false"
              echo "::set-output name=SEND_ALERT::true"
            fi
          fi

      - name: Log outputs  
        run: |
          echo "RERUN=${{ steps.check.outputs.RERUN }}, SEND_ALERT=${{ steps.check.outputs.SEND_ALERT }}"

      - name: Call Rerun API
        if: ${{ steps.check.outputs.RERUN }} == 'true'
        run: |
          curl -X POST -u "ramSeraph:${{secrets.RERUN_PAT}}" ${{ github.event.workflow_run.rerun_url }}

      - name: Send PushBullet notification
        if: ${{ steps.check.outputs.SEND_ALERT }} == 'true'
        run: |
          export PB_TOKEN="${{ secrets.PB_TOKEN }}"
          export REQUEST_BODY="{\"title\":\"LGD Daily run failed\",\"body\":\"LGD Daily Run failed\",\"type\":\"link\", \"url\":\"${{ github.event.workflow_run.html_url}}\"}" 
          curl --header "Access-Token: ${PB_TOKEN}" --header "Content-Type: application/json" --data-binary " --request POST  https://api.pushbullet.com/v2/pushes
