name: Monitor Daily Run
on:
  workflow_run:
    workflows:
      - Daily Run
    types: [completed]

jobs:
  RetryTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check to give up
        id: check
        run: |
          export RUN_ID=${{ github.event.workflow_run.id }}
          export RUN_NO=${{ github.event.workflow_run.run_number }}
          export RUN_ATTEMPT=${{ github.event.workflow_run.run_attempt }}
          export CONCLUSION=${{ github.event.workflow_run.conclusion }}
          echo "got workflow run event for $RUN_NUMBER( attempt - $RUN_ATTEMPT ), conclusion - $CONCLUSION, ${{ toJSON(github.event) }}"
          echo "::set-output name=RERUN::true"
          [ "$CONCLUSION" != "failure" -o "$RUN_ATTEMPT" -lt 3 ] && echo "::set-output name=RERUN::false" || true

      - name: Call Rerun API
        if: ${{ steps.check.outputs.RERUN }} == 'true'
        run: |
          curl -X POST -u "ramSeraph:${{secrets.RERUN_PAT}}" ${{ github.event.worflow_run.rerun_url }}

      - name: Send PushBullet notification
        if: ${{ steps.check.outputs.RERUN }} == 'false'
        uses: yassinebridi/pushbullet-action@v1.0.2
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TYPE: link
          PB_TITLE: LGD Daily Run Failed
          PB_BODY: LGD Daily Run Failed 
          PB_URL: ${{ github.event.workflow_run.html_url }}

