name: Repository Dispatch for rerun
on:
  repository_dispatch:
    types: [retry-trigger]
jobs:
  RetryTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Rerun API
        run: |
          URL=https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.client_payload.run_id }}/rerun
          RUN_ATTEMPT=${{ github.event.client_payload.run_attempt }}
          [ $RUN_ATTEMPT -lt 3 ] && curl -X POST -u "ramSeraph:${{secrets.RERUN_PAT}}" $URL

