name: Repository Dispatch for rerun
on:
  repository_dispatch:
    types: [retry-trigger]
jobs:
  RetryTrigger:
    runs-on: ubuntu-latest
    steps:
      - run: |
        [ ${{ github.event.client_payload.run_attempt }} -lt 3 ] && curl -X POST -H "Authorization: token ${{ secrets.RERUN_PAT }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.client_payload.run_id }}/rerun

