name: SOI Monitor Weekly Pull Run
on:
  workflow_run:
    workflows:
      - SOI Weekly Unavailable Pull Run
    types: [completed]

jobs:
  RetryTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Rerun Or Alert
        uses: ./.github/actions/rerun-trigger
        secrets: inherit
        with:
          alert-title: "SOI Unavailable Run Failed"
          num-attempts: 20
