name: Test Monitor
on:
  workflow_run:
    workflows:
      - Test Run
    types: [completed]

jobs:
  RetryTrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Rerun Or Alert
        uses: ./.github/actions/rerun-trigger
        with:
          alert-title: "Test Run Failed"
          num-attempts: 2
          pb-token: "${{ secrets.PB_TOKEN }}"
          rerun-gh-token: "${{ secrets.RERUN_PAT }}"

